### ISSUE TITLE
Bug in `RandomFourier`

### ISSUE THREAD

**Issue by kahaaga** [JuliaDynamics/TimeseriesSurrogates.jl#104]
**Describe the bug**

RandomFourier does not do what is promises. In the implementation (see below), clearly `ϕ` should not be equal to `r` - it should be the *phases* of `𝓕`, not the amplitudes. I don't know when this error snuck in, but it is a quick fix.

```julia
function (rf::SurrogateGenerator{<:RandomFourier})()
    inverse, m, 𝓕 = getfield.(Ref(rf.init), (:inverse, :m, :𝓕))
    n = length(𝓕)
    r = abs.(𝓕)
    ϕ = abs.(𝓕)
    if rf.method.phases
        randomised_ϕ = rand(rf.rng, Uniform(0, 2π), n)
        new_𝓕 = r .* exp.(randomised_ϕ .* 1im)
    else
        randomised_r = r .* rand(rf.rng, Uniform(0, 2π), n)
        new_𝓕 = randomised_r .* exp.(ϕ .* 1im)
    end
    return inverse*new_𝓕 .+ m
end
```

**Comment by kahaaga** [comment]
I will tag a new version immediately, because this affects end-users.

**Comment by kahaaga** [comment]
Notice: this error only affected `RandomFourier(true)` and `AAFT`, not the other Fourier-based methods.

**Comment by Datseris** [comment]
ok

**Comment by Datseris** [comment]
I guess we better start taking #66 seriously, but let's leave this for after the paper is out

**Comment by kahaaga** [comment]
> I guess we better start taking #66 seriously, but let's leave this for after the paper is out

@datseris Yes, we should at least think about implementing some hypothesis tests, but I'm still a bit reluctant, because it is quite far beyond the scope of what I imagined this package would be. It could be a paper in itself to develop a good set of benchmark tests that the surrogate methods should pass.
