### ISSUE TITLE
The multidimensional surrogate example plot is empty

### ISSUE THREAD

**Issue by kahaaga** [JuliaDynamics/TimeseriesSurrogates.jl#135]
## Describe the bug

In the [documentation](https://juliadynamics.github.io/TimeseriesSurrogates.jl/stable/) for the stable branch, the multidimensional surrogate example plot is empty. 

I'm marking this a good first issue.

**Comment by sathvikbhagavan** [comment]
The plot is empty because the values of 

`CX = correlationsum(X, e; w = 5)` has zeros in it due to which the log of them is `Inf` 

which is getting plotted in

`fig, ax = lines(le, log10.(CX))`

**Comment by sathvikbhagavan** [comment]
Should this be plotted without log? I can make a small PR for that

**Comment by kahaaga** [comment]
> Should this be plotted without log? I can make a small PR for that

@sathvikbhagavan It would be excellent if you could submit a PR that fixes the plot. 

I think the purpose of the correlation sum plot is to inspect the curve in log-log space (perhaps @Datseris can correct me here if I'm wrong), so removing the log is perhaps not the best idea. However, Makie.jl has the option to use so-called ["pseudolog" axes](https://docs.makie.org/stable/examples/blocks/axis/index.html#pseudolog_and_symlog_scales). Perhaps you could give that a try?
