### ISSUE TITLE
both StateSpaceSets and StatsBase export "standardize"; uses of it in module TimeseriesSurrogates must be qualified

### ISSUE THREAD

**Issue by jerlich** [JuliaDynamics/TimeseriesSurrogates.jl#148]
This isn't a bug. I saw a warning:

`both StateSpaceSets and StatsBase export "standardize"; uses of it in module TimeseriesSurrogates must be qualified`

that I thought I would share. 

I apologise, I don't have a MWE - I am using DynamicalSystems.jl in a Pluto notebook and it popped up. I tried to make an MWE but I couldn't make the warning appear again.

OS: Mac (M1)
Julia: Version 1.9.0-rc3 (2023-04-26)
```
  [cbdf2221] AlgebraOfGraphics v0.6.14
  [f3fd9213] Attractors v1.5.1
  [13f3f980] CairoMakie v0.10.4
  [1313f7d8] DataFramesMeta v0.14.0
⌃ [31c24e10] Distributions v0.25.88
  [61744808] DynamicalSystems v3.0.0
⌅ [1dea7af3] OrdinaryDiffEq v6.50.0
  [7f904dfe] PlutoUI v0.7.51
⌅ [2913bbd2] StatsBase v0.33.21
  [ac1d9e8a] ThreadsX v0.1.11
  [44cfe95a] Pkg v1.9.0
```

**Comment by Datseris** [comment]
Thank you, we are aware of this, but there is nothing to be done. We have made the decision that the name `standardize` is the most suitable name for this function. StatsBase thinks their name the most suitable name for their function, but their function does different things. Your only option is to do what the warning message instructs you to:

1. Either always preface all function calls with `StateSpaceSets.standardize`
2. Or two, define `standardize = StateSpaceSets.standardize`.

**Comment by Datseris** [comment]
(okay, in case it wasn't clear: the warning appears because both our package as well as the StatsBase.jl package define and export a function called `standardize`. So Julia doesn't know which of the two to use when you write `standardize(x)`)

**Comment by jerlich** [comment]
The funny thing is that I was not calling the function. It must be called (without qualification) from another module I was using.

**Comment by Datseris** [comment]
Not necessary, Julia will display this warning for all conficting names regardless of if they have been used or not. The goal is to warn you _before_ using it, so that you don't get unexpected errors
