### ISSUE TITLE
[Minor] Incorrect documentation link for Documenter.jl

### ISSUE THREAD

**Issue by smidmatej** [JuliaDynamics/TimeseriesSurrogates.jl#150]
At https://juliadynamics.github.io/TimeseriesSurrogates.jl/stable/, the hypertext link reads "[Crash-course into timeseries surrogate tests](https://juliadynamics.github.io/TimeseriesSurrogates.jl/stable/@ref)" however, the page it is trying to refer to reads "Crash-course in timeseries surrogate testing"

Clicking the link leads to 404.

 I tried making a fork and changing the name myself for a pull request, but I probably need to run Documenter.jl on the repo to generate the documentation and see if I was successful.

**Comment by kahaaga** [comment]
Hi, @smidmatej! Thanks for letting us know. If you submit a PR to this repo with your updates, the docs should build automatically, and you can verify that the updated link works. 

Remember to tick off "maintainers can edit this PR" (or whatever the option is), in case we need to make some changes in order for the docs to run.

**Comment by Datseris** [comment]
> If you submit a PR to this repo with your updates, the docs should build automatically, and you can verify that the updated link works.

Note: docs build deploy when a PR is does from a branch of the repo, not from a fork. Because deploying docs requires GitHub token access. Neverhteless, the fix to this issue is so simple that we do not require to preview docs, reading the markdown changes is enough.

**Comment by kahaaga** [comment]
> Note: docs build deploy when a PR is does from a branch of the repo, not from a fork. Because deploying docs requires GitHub token access.

Ah, that makes sense! Thanks for the reminder. 

> Neverhteless, the fix to this issue is so simple that we do not require to preview docs, reading the markdown changes is enough.

Yes, a regular PR from the fork should suffice.

**Comment by kahaaga** [comment]
Fixed in #156
