### ISSUE TITLE
Figures for last "Crash-course in timeseries surrogate testing"  doc page not generated

### ISSUE THREAD

**Issue by kahaaga** [JuliaDynamics/TimeseriesSurrogates.jl#157]
Under the "An educative example" heading, the example blocks don't run successfully. Hence, the figure that is supposed to be shown there isn't either. 

This is likely either due to some syntax error, that some error is thrown by the code example, or that a package used in the example is missing from `docs/Project.toml`,

**Comment by sathvikbhagavan** [comment]
The docs are building fine. It was erroring due to a makie error - https://github.com/JuliaDynamics/TimeseriesSurrogates.jl/actions/runs/6378562490/job/17309367622#step:8:277, but I think it was fixed - https://github.com/MakieOrg/Makie.jl/issues/3266
So, retriggering it on master should fix it.

**Comment by kahaaga** [comment]
Thanks for the info, @sathvikbhagavan! I re-triggered the documentation build, so fingers crossed that it works now.

**Comment by kahaaga** [comment]
Excellent. Figures are now generated.
