### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by kahaaga** [JuliaDynamics/TimeseriesSurrogates.jl#26]
Use a single `surrogate(x, method::Surrogate)` function that dispatches on different surrogate types (e.g. `Shuffle`, `AAFT`, `IAAFT`). 

See discussion in #24 (@Datseris)

**Comment by Datseris** [comment]
Notice also how this API is generalizable to more complicated methods.

If you imagine a method that has some configuration parameters, these are given to the method struct, e.g. `SomeFancyMethod(0.5, 0.2)`, so the top-most function call remains the same `surrogate(x, fancy_method)`.

**Comment by kahaaga** [comment]
Done in #38.
