### ISSUE TITLE
Method request: PPS surrogates

### ISSUE THREAD

**Issue by kahaaga** [JuliaDynamics/TimeseriesSurrogates.jl#27]
Implement the pseudoperiodic surrogates (PPS) from [Small, M., Yu, D., & Harrison, R. G. (2001). Surrogate Test for Pseudoperiodic Time Series Data. Physical Review Letters, 87(18). doi:10.1103/physrevlett.87.188101](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.87.188101). 

The method should follow the new API once that is done. That is, `surrogate(x, method::PPS)` with an associated type `PPS` with fields `τ` and `d` controlling the delay and dimension of the reconstructed embedding. Use `genembed` from DynamicalSystems for the embedding.

See discussion in #24 (@datseris)

**Comment by Datseris** [comment]
I've implemented this method. I'll wait until #32 is finished and then I'll PR it here.

**Comment by kahaaga** [comment]
Ongoing in #37

**Comment by kahaaga** [comment]
@Datseris This is ready to close now, right? Or do you have additional tests/features that you want to implement for the method first?
