### ISSUE TITLE
Method request: truncated fourier transform surrogates

### ISSUE THREAD

**Issue by kahaaga** [JuliaDynamics/TimeseriesSurrogates.jl#28]
Implement the TFTS and STFTS surrogate methods from [Small, M., Yu, D., & Harrison, R. G. (2001). Surrogate Test for Pseudoperiodic Time Series Data. Physical Review Letters, 87(18). doi:10.1103/physrevlett.87.188101 ](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.74.026205).

The implementations should follow the new API (#26) with a `surrogate(x, method::TFTS)` and `surrogate(x, method:STFTS)` with an associated types `TFTS` and `STFTS` that both store information about the desired frequency domain `fϵ`. 

See discussion in #24 (@Datseris)

**Comment by Datseris** [comment]
This blogpost: https://sapienlabs.org/using-surrogate-data-to-detect-nonlinearity-in-time-series/  claims that this repo: https://github.com/narayanps/NolinearTimeSeriesAnalysis  has a Python implementation of TFT (if needed for reference)

**Comment by kahaaga** [comment]
@datseris I had a more thorough look at the paper. It may be pretty straight-forward to implement the truncated fourier transform surrogate methods based on the existing code - I think one just has to do a few extra steps during the phase shuffling.  I've started working on an implementation. Will keep you updated!

**Comment by Datseris** [comment]
I guess related: https://journals.aps.org/pre/abstract/10.1103/PhysRevE.85.056202

**Comment by kahaaga** [comment]
Still work in progress, but getting somewhere:

```julia
n = 1000
a = 0.2
A = 15
σ = 10
x = cumsum(randn(n)) .+ [1 + a*i .+ A*sin(2π/30*i) for i = 1:n] .+ σ .* rand(n) .+ rand(n);
fϵ = 0.0
method = TFTS(x, fϵ, M = 3);
s = surrogate(x, method)

surrplot(x, s)
```

![Screenshot 2020-05-12 06 16 08](https://user-images.githubusercontent.com/5237566/81638082-52f2ef00-9418-11ea-8380-1c2a266c0718.png)

but with some truncation using `fϵ = 0.1` I get

![Screenshot 2020-05-12 06 18 32](https://user-images.githubusercontent.com/5237566/81638121-6e5dfa00-9418-11ea-96be-bf428b0faf1b.png)

Not quuite sure if I've understood the procedure completely yet, but it seems to do what it promises. 

Assuming my implementation is correct, the issue of endpoint mismatch gets quite severe if the trend is strong, so I will see if the paper you linked has some improvements.

**Comment by Datseris** [comment]
Oh wow, that is **amazing**! Nice! I could totally use this method in my work! Looking forward to you adding it!
