### ISSUE TITLE
Use ARFIMA.jl in favor of defining models?

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/TimeseriesSurrogates.jl#33]
I can move ARFIMA.jl to JuliaDynamics and instead of re-inventing the wheel and defining models here we could just use it in the docs or just cite it in the docs.

https://github.com/Datseris/ARFIMA.jl

**Comment by Datseris** [comment]
Ah, I see now that the systems are not the trivial ARFIMA but nonlinear ones...

Still, should be useful to cite ARFIMA.jl.

**Comment by kahaaga** [comment]
The surrogate methods are also conceptually different in that they simulate time series _based on other time series_, instead of generating them from parameterized models. A reference to ARFIMA.jl is in the documentation would be useful to highlight this difference.
