### ISSUE TITLE
Plotting recipe idea

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/TimeseriesSurrogates.jl#40]
I wonder, wouldn't it be great if we allowed more than 1 surrogates to be part of the recipe?

Something like `surrogateplot(x, args...)` with args several surrogates. We go back to 4 subplots, and the last one has all histograms with alpha.

**Comment by kahaaga** [comment]
> I wonder, wouldn't it be great if we allowed more than 1 surrogates to be part of the recipe?

Multiple surrogates in the recipe is a great idea!

> Something like `surrogateplot(x, args...)` with args several surrogates. We go back to 4 subplots, and the last one has all histograms with alpha.

Not sure about the histograms with the `alpha`, though. I experimented a bit, but it looks messy to me with the overlays. If you can come up with a nice recipe for the histograms, I'm not entirely opposed to it, though!

**Comment by Datseris** [comment]
I have been thinking about this in general, and I must admit I am skeptical on whther we should provide plotting recipies in such a small, self-contained package. Couldn't we get away by simply defining a function in the docs and using it to plot a couple of examples?

In the end of the day, we are not defining any new plotting recipe. We just use timeseries, histograms, and fourier transforms.

**Comment by Datseris** [comment]
This would also allow us to use KernelDensity (an extremely heavy dependency) in the docs for the recipy.

**Comment by kahaaga** [comment]
At the moment, I think the `surroplot` function makes a decent job at demonstrating the different methods in the docs, so I don't think we need anything more complicated. I favour keeping `surroplot`, because it gives the user a quick way to verify that the most common surrogate methods work/don't work on their data, and allows them to replicate the docs easily.
