### ISSUE TITLE
Strange behaviour for PseudoPeriodic surrogates

### ISSUE THREAD

**Issue by kahaaga** [JuliaDynamics/TimeseriesSurrogates.jl#45]
(I'm on the `docs`branch, see #39 )

For certain time series 

```julia
using TimeseriesSurrogates
ts = NSAR2() # create a realization of an NSAR2 process
phases = true

# Embedding parameters need to be specified
d, τ, ρ = 3, 2, 0.05
method = PseudoPeriodic(d, τ, ρ)
s = surrogate(ts, method)

surrplot(ts, s)
```
gives 

![Screenshot 2020-05-12 05 50 34](https://user-images.githubusercontent.com/5237566/81636718-d6124600-9414-11ea-88b1-f7a82b3aed0f.png)

@Datseris Any idea why the orbit gets stuck in a small neighborhood? I am just naively picking some random value for `ρ` here, so it might just be because of my ignorance, but I seem to be able to reproduce this for different values of `ρ`. 

If this is an issue inherent to the algorithm, perhaps this should be mentioned in the `PseudoPeriodic` docstring, or even discussed on the `PseudoPeriodic` page.

**Comment by Datseris** [comment]
I don't think it makes sense to use `PseudoPeriodic` with such timeseries. The method really targets periodic orbits, or approximately periodic orbits, with added noise on top. I.e. there must be a clear signal, or huge peaks in the fourier transform, for it to work.

**Comment by Datseris** [comment]
Okay, I now what is happening here, gimme a second.

**Comment by Datseris** [comment]
Yeap:
```julia
function pseudoperiodic!(y, x, z, w, ρ, shift)
    N, Ñ = length.((x, z))
    y[1] = shift ? rand(z.data) : z[1]
    @inbounds for i in 1:N-1
        w .= (exp(-norm(z[t] - y[i])/ρ) for t in 1:Ñ-1)
        j = sample(1:Ñ-1, pweights(w))
        y[i+1] = z[j+1]
    end
    return y[:, 1]
end
```

What I guess happens is that you always get the same `j` in that algorithm after some point. I don't think it is worth fixing it though: too complicated to try and put several if statements, and keeping track of which indices have already been used. For me it is clear that the method failed here because it wasn't used with suitable timeseries in the first place.

**Comment by kahaaga** [comment]
This method works for the intented type of time series. Closing.
