### ISSUE TITLE
[DOC] Mention conserved property and suitable hypothesis

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/TimeseriesSurrogates.jl#58]
I think since we already know this information it could be helpful to add it to the docstring. So for each Surrogate method in the docstring we add:

1. What property of the timeseries is conserved.
2. What null hypothesis is the method suitable to test.

(1) is mostly done, most methods have it but some miss it. (2) I think we haven't done at all.

**Comment by kahaaga** [comment]
The docs bould be a bit clearer for (1), and suitable null hypothesis should indeed be added.  I'll have a go at both.
