### ISSUE TITLE
Error when generating docs locally

### ISSUE THREAD

**Issue by kahaaga** [JuliaDynamics/TimeseriesSurrogates.jl#91]
@Datseris I just got the following error message when building the docs locally, in a fresh session. It seems to be related to theme compiling. Maybe this is related to why the docs have been taking > 1.5 hours to run in GitHub actions the past few days. 

Have you seen this error before? 

```Julia
 include("docs/make.jl")
ERROR: LoadError: UndefVarError: libsass_so not defined
Stacktrace:
 [1] sass_make_file_context(filename::String)
   @ Sass ~/.julia/packages/Sass/K4Tzw/src/context.jl:16
 [2] compile_file(filename::String; input_path::String, source_map_file::Nothing, kwargs::Base.Pairs{Symbol, String, Tuple{Symbol, Symbol}, NamedTuple{(:output_path, :include_path), Tuple{String, String}}})
   @ Sass ~/.julia/packages/Sass/K4Tzw/src/julian_api.jl:53
 [3] #compile_file#2
   @ ~/.julia/packages/Sass/K4Tzw/src/julian_api.jl:85 [inlined]
 [4] compile(src::String, dst::String)
   @ DocumenterTools.Themes ~/.julia/packages/DocumenterTools/m8nQ0/src/Themes.jl:50
 [5] top-level scope
   @ ~/Code/Repos/TimeseriesSurrogates.jl/docs/make.jl:29
 [6] include(fname::String)
   @ Base.MainInclude ./client.jl:451
 [7] top-level scope
   @ REPL[4]:1
in expression starting at [....]/TimeseriesSurrogates.jl/docs/make.jl:29
```

**Comment by Datseris** [comment]
I'll try to resolve this, but can't promise yet if I can manage to do it before the next weekend :(

**Comment by kahaaga** [comment]
> I'll try to resolve this, but can't promise yet if I can manage to do it before the next weekend :(

No problem. It is not a critical issue. For some reason, the docs are still building successfully in Github actions, so I'm not sure why this happens locally.
