### ISSUE TITLE
Rename `LS` to something better

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/TimeseriesSurrogates.jl#93]
@kahaaga please provide a better name for `LS`. This is way too short and rather cryptic. Doesn't convey anything. Also notice that in the documentation of `LS` there is no mentioning to the name "Lomb Scargle", so I am really not sure how I user would make the connection "LS = LombScargle".

**Comment by Datseris** [comment]
`LombScargle` is also a Julia package so our name cannot be this exactly

**Comment by kahaaga** [comment]
@datseris How about `IrregularLombScargle` or something along those lines? That keeps naming potential other methods like `IrregularSomeOtherMethod` that we might implement simple.

**Comment by Datseris** [comment]
yeah that's ok

**Comment by kahaaga** [comment]
Closed with #100
